# Generated by Django 3.1.4 on 2021-01-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='fees_in_usa',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='fess_in_world',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='world_premiere',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
    ]
